---
abstract: 'Tied construct for hash key checking.'
author:
  - 'Michal Spacek <skim@cpan.org>'
build_requires:
  English: 0
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.01
  Test::More: 0
  Test::NoWarnings: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.14'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tie-Hash-Check
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  Error::Pure: 0.18
  Error::Pure::Utils: 0.18
  perl: 5.6.0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Tie-Hash-Check
  homepage: https://github.com/tupinek/Tie-Hash-Check
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/tupinek/Tie-Hash-Check
version: '0.02'
